config/routes.rb
Rails.application.routes.draw do
  root to: 'home#welcome'
  devise_for :users
  resources :quantities
  resources :categories 
  resources :ingredients
  resources :recipes
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :recipes
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :quantities
  has_many :recipes, through: :quantities
  #has_and_belongs_to_many :recipes
end

app/models/quantity.rb
class Quantity < ActiveRecord::Base
  belongs_to :ingredient
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :quantities
  belongs_to :category
  has_many :ingredients, through: :quantities
  #has_and_belongs_to_many :ingredients
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = Category.all
  end

  def update
    category = Category.find(params[:id])
    category.update(category_params)
    redirect_to(categories_path)
  end

  def new
    @category = Category.new
  end

  def create
    Category.create(category_params)
    redirect_to(categories_path)
  end

  def show
    @category = Category.find(params[:id])
  end

  def destroy
    @category = Category.find(params[:id])
    category.destroy
    redirect_to(category_path)
  end

  def edit
    @category = Category.find(params[:id])
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def welcome
    
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :authenticate_user!
  def index
    @ingredients = Ingredient.all
  end

  def update
    ingredient = Ingredient.find(params[:id])
    ingredient.update(ingredient_params)
    redirect_to(ingredients_path)
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    Ingredient.create(ingredient_params)
    redirect_to(ingredients_path)
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end

  def destroy
    @ingredient = Ingredient.find(params[:id])
    ingredient.destroy
    redirect_to(ingredients_path)
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  private
  def ingredient_params
    params.require(:ingredient).permit(:name, :location, :description, {recipe_ids: []})
  end

end

app/controllers/quantities_controller.rb
class QuantitiesController < ApplicationController
  before_action :set_quantity, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /quantities
  # GET /quantities.json
  def index
    @quantities = Quantity.all
  end

  # GET /quantities/1
  # GET /quantities/1.json
  def show
  end

  # GET /quantities/new
  def new
    @quantity = Quantity.new
  end

  # GET /quantities/1/edit
  def edit
  end

  # POST /quantities
  # POST /quantities.json
  def create
    @quantity = Quantity.new(quantity_params)

    respond_to do |format|
      if @quantity.save
        format.html { redirect_to @quantity, notice: 'Quantity was successfully created.' }
        format.json { render :show, status: :created, location: @quantity }
      else
        format.html { render :new }
        format.json { render json: @quantity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quantities/1
  # PATCH/PUT /quantities/1.json
  def update
    respond_to do |format|
      if @quantity.update(quantity_params)
        format.html { redirect_to @quantity, notice: 'Quantity was successfully updated.' }
        format.json { render :show, status: :ok, location: @quantity }
      else
        format.html { render :edit }
        format.json { render json: @quantity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quantities/1
  # DELETE /quantities/1.json
  def destroy
    @quantity.destroy
    respond_to do |format|
      format.html { redirect_to quantities_url, notice: 'Quantity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quantity
      @quantity = Quantity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quantity_params
      params.require(:quantity).permit(:ingredient_id, :recipe_id, :quantity)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!
  def index
    @recipes = Recipe.all
  end

  def update
    recipe = Recipe.find(params[:id])
    recipe.update(recipe_params)
    redirect_to(recipes_path)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    Recipe.create(recipe_params)
    redirect_to(recipes_path)
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    recipe.destroy
    redirect_to(recipes_path)
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  private
  def recipe_params
    params.require(:recipe).permit(:name, :category_id, :description, :instructions, {ingredient_ids: []})
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quantities_helper.rb
module QuantitiesHelper
end

app/views/categories/_form.html.erb
<div class="category_form">
<%= form_for @category do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name  %>
  <br>
  <%= f.submit 'Cast away!' %>
<% end %>
</div>

app/views/categories/edit.html.erb
<%= render partial: "form" %>

app/views/categories/index.html.erb
<div class="category_index">
<% @categories.each do |category| %>

 <strong> <%=  category.name %> </strong>

  <%= button_to('Destroy Element', category_path(category), method: :delete, data: {confirm: 'Destroy Element? Are you sure?'}) %>

  <%= link_to('Edit Element', edit_category_path(category)) %>
  <br>
  <br>
<% end %>
<%= link_to('New Element', new_category_path(@category)) %>
</div>

app/views/categories/new.html.erb
<%= render partial: "form" %>

app/views/categories/show.html.erb
<div class="show">
  <h1><%= @category.name %></h1>
</div>

app/views/home/welcome.html.erb
<div class="navbar">
  <h1>Mystery Pete's Magic Book</h1>
  <h3>Your number 1 resource for all things magic!</h3>
</div>

app/views/ingredients/_form.html.erb
<%= form_for @ingredient do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name  %>
  <br>
  <%= f.label :location %>
  <%= f.text_field :location %>
  <br>
  <%= f.label :description %>
  <%= f.text_field :description  %>
  <br>
  <%= f.submit 'Cast away!' %>
<% end %>

app/views/ingredients/edit.html.erb
<%= render partial: "form" %>

app/views/ingredients/index.html.erb
<div class="menu_show">

  <% @ingredients.each do |ingredient| %>

  <%= link_to("Show #{ingredient.name}", ingredient_path(ingredient) )%>

  <%= button_to('Destroy Ingredient', ingredient_path(ingredient), method: :delete, data: {confirm: 'Destroy Ingredient? Are you sure?'}) %>

  <%= link_to('Edit Ingredient', edit_ingredient_path(ingredient))%>

  <br>
  <br>
  <% end %>

  <%= link_to('New Ingredient', new_ingredient_path(@ingredient)) %>
</div>

app/views/ingredients/new.html.erb
<%= render partial: "form" %>

app/views/ingredients/show.html.erb
<div class="show">
  <h1><%= @ingredient.name %></h1>
  <p><%= @ingredient.location %></p>
  <p><%= @ingredient.description %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Magic Book</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>



  <div class="menu">
    <nav>
      <ul>
        <li> <%= link_to('Home', root_path) %> </li>      
        <li> <%= link_to('Recipes', recipes_path) %> </li>
        <li> <%= link_to('Elements', categories_path) %> </li>
        <li> <%= link_to('Ingredients', ingredients_path) %> </li>
        <li><%=link_to 'Quantities', quantities_path %></li>  
      </ul>
    </nav>
  </div>

  <audio controls>
    <source src="magic.mp3" typw="mp3"
  </audio>

</body>
</html>

app/views/quantities/_form.html.erb
<%= form_for(@quantity) do |f| %>
  <% if @quantity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quantity.errors.count, "error") %> prohibited this quantity from being saved:</h2>

      <ul>
      <% @quantity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ingredient_id %><br>
    <%= f.collection_select(:ingredient_id, Ingredient.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :recipe_id %><br>
    <%= f.collection_select(:recipe_id, Recipe.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.text_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quantities/edit.html.erb
<h1>Editing Quantity</h1>

<%= render 'form' %>

<%= link_to 'Show', @quantity %> |
<%= link_to 'Back', quantities_path %>

app/views/quantities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Quantities</h1>

<table>
  <thead>
    <tr>
      <th>Ingredient</th>
      <th>Recipe</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quantities.each do |quantity| %>
      <tr>
        <td><%= quantity.ingredient.try(:name) %></td>
        <td><%= quantity.recipe.try(:name) %></td>
        <td><%= quantity.quantity %></td>
        <td><%= link_to 'Show', quantity %></td>
        <td><%= link_to 'Edit', edit_quantity_path(quantity) %></td>
        <td><%= link_to 'Destroy', quantity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quantity', new_quantity_path %>

app/views/quantities/new.html.erb
<h1>New Quantity</h1>

<%= render 'form' %>

<%= link_to 'Back', quantities_path %>

app/views/quantities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ingredient:</strong>
  <%= @quantity.ingredient.try(:name) %>
</p>

<p>
  <strong>Recipe:</strong>
  <%= @quantity.recipe.try(:name) %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @quantity.quantity %>
</p>

<%= link_to 'Edit', edit_quantity_path(@quantity) %> |
<%= link_to 'Back', quantities_path %>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category_id, 'Category' %><br>
    <%= f.collection_select(:category_id, Category.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :instructions %><br>
    <%= f.text_area :instructions %>
  </div>

  <div class="field">
    <%= f.collection_check_boxes :ingredient_ids, Ingredient.all.order(:name), :id, :name %><br>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<%= render partial: "form" %>

app/views/recipes/index.html.erb
<div class="menu_show">
<% @recipes.each do |recipe| %>

  <strong><%= link_to("Show #{recipe.name}", recipe_path(recipe) )%></strong>
  <%= link_to('Edit Recipe', edit_recipe_path(recipe)) %>
  <%= button_to('Destroy Recipe', recipe_path(recipe), method: :delete, data: {confirm: 'Destroy Recipe? Are you sure?'}) %>
  <br>
  <br>
<% end %>
<%= link_to('New Recipe', new_recipe_path(@recipe)) %>
</div>

app/views/recipes/new.html.erb
<%= render partial: "form" %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @recipe.category.try :name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @recipe.description %>
</p>

<p>
  <strong>Instructions:</strong>
  <%= @recipe.instructions %>
</p>

<p>
  <strong>Ingredients:</strong><br>
  <% @recipe.quantities.each do |quantity| %>
    <%= quantity.quantity %>
    <%= quantity.ingredient.try(:name) %><br>
  <% end %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>